package com.sentinel.casemanagementservice.model;

import com.sentinel.sentinelcommons.enums.FraudDecision;
import com.sentinel.sentinelcommons.enums.RiskLevel;
import com.sentinel.sentinelcommons.enums.TransactionStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.Version;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDateTime;


/**
 * JPA entity representing a fraud case.
 *
 * A fraud case is created for every HIGH or CRITICAL
 * transaction that passes through the scoring service.
 * It represents the human review workflow — an analyst
 * examines the evidence and makes a final decision.
 *
 * Database design decisions:
 *
 * PRIMARY KEY = transactionId
 * One case per transaction. Using the transaction ID
 * as the primary key prevents duplicate cases for
 * the same transaction and makes lookups by transaction
 * ID O(1) without a separate index.
 *
 * OPTIMISTIC LOCKING (@Version)
 * Multiple analysts might try to update the same case
 * simultaneously. @Version adds a version column to the
 * table. If two analysts load version 1 and both try
 * to update — the first succeeds (version becomes 2),
 * the second gets an OptimisticLockException because
 * the version they loaded (1) no longer matches.
 * No deadlocks, no lost updates, no dirty reads.
 *
 * INDEXES
 * Queries are built around:
 * - accountId    (analyst looks up all cases for an account)
 * - status       (analyst dashboard filters by OPEN/RESOLVED)
 * - riskLevel    (priority queue — CRITICAL first)
 * - createdAt    (chronological ordering)
 * Composite index on (status, riskLevel) optimises the
 * most common analyst query: "show me open CRITICAL cases"
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(
        name = "fraud_cases",
        indexes = {
                @Index(
                        name = "idx_case_account_id",
                        columnList = "accountId"
                ),
                @Index(
                        name = "idx_case_status",
                        columnList = "status"
                ),
                @Index(
                        name = "idx_case_risk_level",
                        columnList = "riskLevel"
                ),
                @Index(
                        name = "idx_case_created_at",
                        columnList = "createdAt"
                ),
                @Index(
                        name = "idx_case_status_risk",
                        columnList = "status, riskLevel"
                )
        }
)
public class FraudCase {

    /**
     * Case ID — format: CASE-{transactionId prefix}
     * Generated by scoring-service, passed through
     * FraudAlertEvent.
     */
    @Id
    @Column(nullable = false, updatable = false)
    private String caseId;

    /**
     * The transaction this case relates to.
     * Unique — one case per transaction.
     */
    @Column(nullable = false, updatable = false, unique = true)
    private String transactionId;

    /**
     * The account that initiated the transaction.
     * Indexed for account-level fraud history queries.
     */
    @Column(nullable = false)
    private String accountId;

    /**
     * The merchant or recipient.
     * Used to increment recipient risk counter in Redis
     * when fraud is confirmed.
     */
    @Column(nullable = true)
    private String merchantId;

    /**
     * Combined fraud score (0-100) from rules engine
     * + Groq AI.
     */
    @Column(nullable = false)
    private int fraudScore;

    /**
     * Risk level derived from fraud score.
     * Stored as STRING in DB — human readable,
     * not dependent on enum ordinal position.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private RiskLevel riskLevel;

    /**
     * Current case status.
     * FLAGGED   → awaiting analyst review
     * BLOCKED   → automatically blocked, analyst confirms
     * APPROVED  → analyst cleared this transaction
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionStatus status;

    /**
     * What the analyst decided.
     * Null until analyst acts on the case.
     */
    @Enumerated(EnumType.STRING)
    @Column
    private FraudDecision analystDecision;

    /**
     * Rules that fired during evaluation.
     * Stored as comma-separated string.
     * Example: "VELOCITY_CHECK,MERCHANT_CATEGORY_RISK"
     */
    @Column(columnDefinition = "TEXT")
    private String triggeredRules;

    /**
     * Combined explanation from rules engine + Groq AI.
     * Full text for analyst review.
     * columnDefinition = "TEXT" allows unlimited length
     * unlike VARCHAR which has a 255 char default.
     */
    @Column(columnDefinition = "TEXT")
    private String aiExplanation;

    /**
     * Optional notes from the analyst explaining
     * their decision. Feeds into model training.
     */
    @Column(columnDefinition = "TEXT")
    private String analystNotes;

    /**
     * When this case was created.
     * Indexed for chronological ordering.
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * When the analyst made their decision.
     * Null until resolved.
     */
    @Column
    private LocalDateTime resolvedAt;

    /**
     * Optimistic locking version column.
     * Prevents concurrent update conflicts.
     * Incremented automatically by Hibernate
     * on every update.
     */
    @Version
    @Column(nullable = false)
    private Long version;
}