# =====================================================
# APPLICATION IDENTITY
# Spring uses this name in logs and monitoring tools.
# Grafana and Zipkin will label this service by this name.
# =====================================================
spring.application.name=api-gateway

# =====================================================
# SERVER PORT
# Port 8080 is the single entry point for all traffic.
# All external clients (web dashboard, partner APIs)
# send requests here ? the gateway routes them onward.
# =====================================================
server.port=8080

# =====================================================
# ROUTING RULES
# These tell the gateway where to forward requests.
# Any request to /api/v1/transactions/** goes to the
# ingestion service running on port 8081.
# Any request to /api/v1/cases/** goes to case
# management service running on port 8084.
# =====================================================
spring.cloud.gateway.routes[0].id=ingestion-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/transactions/**



spring.cloud.gateway.routes[1].id=case-management-service
spring.cloud.gateway.routes[1].uri=http://localhost:8084
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/cases/**

# =====================================================
# ACTUATOR
# Exposes the /actuator/health endpoint.
# Kubernetes calls this to check if the gateway
# pod is alive and ready to accept traffic.
# =====================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always