# =====================================================
# APPLICATION IDENTITY
# =====================================================
spring.application.name=rules-engine-service

# =====================================================
# SERVER PORT
# =====================================================
server.port=8082

# =====================================================
# KAFKA CONFIGURATION
# =====================================================
spring.kafka.bootstrap-servers=localhost:9092

# CONSUMER CONFIG
# group-id ? identifies this service as a consumer group.
# All instances of rules-engine-service share this group ID
# so Kafka delivers each message to only one instance,
# preventing duplicate processing.
spring.kafka.consumer.group-id=rules-engine-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# trusted-packages ? security setting that tells the
# JsonDeserializer which Java packages it is allowed
# to deserialize. We trust our own com.sentinel package.
spring.kafka.consumer.properties.spring.json.trusted.packages=com.sentinel.*

# auto-offset-reset ? if this service starts and there
# are already messages in Kafka it hasn't seen,
# "earliest" means start from the beginning.
spring.kafka.consumer.auto-offset-reset=earliest

# =====================================================
# ACTUATOR
# =====================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


# =====================================================
# KEEP APPLICATION ALIVE
# This service has no web server ? it runs as a
# background Kafka consumer. Without this, Spring Boot
# starts and immediately shuts down because it thinks
# there is nothing to do. This keeps the JVM running
# so the service stays alive waiting for Kafka messages.
# =====================================================
spring.main.keep-alive=true