# =====================================================
# APPLICATION IDENTITY
# =====================================================
spring.application.name=ingestion-service

# =====================================================
# SERVER PORT
# =====================================================
server.port=8081

# =====================================================
# KAFKA CONFIGURATION
# Points to the Kafka broker running in Docker Compose.
# localhost:9092 is where Kafka will be available
# when docker-compose.yml is running.
# =====================================================
spring.kafka.bootstrap-servers=localhost:9092

# PRODUCER CONFIG
# key-serializer ? the transaction ID (a String) is
# used as the Kafka message key.
# value-serializer ? the transaction object is
# serialized to JSON before sending to Kafka.
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# =====================================================
# ACTUATOR
# =====================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# =====================================================
# SWAGGER / OPENAPI
# API docs available at:
# http://localhost:8081/swagger-ui/index.html
# =====================================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
