apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: sentinel
data:
  application-kubernetes.properties: |
    spring.cloud.gateway.routes[0].id=ingestion-service
    spring.cloud.gateway.routes[0].uri=http://ingestion-service:8081
    spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/transactions/**
    spring.cloud.gateway.routes[1].id=case-management-service
    spring.cloud.gateway.routes[1].uri=http://case-management-service:8084
    spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/cases/**
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: sentinel
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: lemmy007/sentinel-api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: "api-gateway"
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
          volumeMounts:
            - name: gateway-config
              mountPath: /app/config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: gateway-config
          configMap:
            name: api-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: sentinel
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080