# =====================================================
# APPLICATION IDENTITY
# =====================================================
spring.application.name=case-management-service
server.port=8084

# =====================================================
# POSTGRESQL
# Port 5433 ? avoids conflict with local PostgreSQL
# =====================================================
spring.datasource.url=jdbc:postgresql://localhost:5433/sentinel_cases
spring.datasource.username=sentinel
spring.datasource.password=sentinel123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA ? Hibernate creates/updates tables automatically
# In production use "validate" with Flyway migrations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# =====================================================
# REDIS
# =====================================================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# =====================================================
# KAFKA
# =====================================================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=case-management-group
spring.kafka.consumer.auto-offset-reset=earliest

# =====================================================
# KAFKA TOPICS
# =====================================================
sentinel.kafka.topics.fraud-alerts=fraud.alerts
sentinel.kafka.topics.model-feedback=model.feedback

# =====================================================
# ACTUATOR
# =====================================================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always

# =====================================================
# SWAGGER
# =====================================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html