package com.sentinel.ingestionservice.mapper;

import com.sentinel.sentinelcommons.enums.TransactionStatus;
import com.sentinel.sentinelcommons.event.TransactionEvent;
import com.sentinel.ingestionservice.dto.TransactionRequest;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Converts between DTOs and Kafka events.

 * Why a separate mapper class?
 * The controller should not know about Kafka events.
 * The service should not know about HTTP request format.
 * The mapper sits between them and handles the conversion.

 * This separation means:
 * - If the HTTP request format changes, only the mapper changes
 * - If the Kafka event format changes, only the mapper changes
 * - Controller and service stay untouched
 *
 * @Component registers this as a Spring bean so it can
 * be injected wherever needed.
 */
@Component
public class TransactionMapper {

    /**
     * Converts an inbound HTTP request into a Kafka event.

     * This is where we ENRICH the data — the caller sends
     * the business data (accountId, amount, etc.) but we
     * add the operational data:
     * - transactionId: generated by us, not the caller
     * - status: always RECEIVED on ingestion
     * - timestamp: when WE received it, not when they sent it

     * The transactionId uses UUID.randomUUID() which is
     * thread-safe — safe to call from concurrent requests.
     */
    public TransactionEvent toEvent(TransactionRequest request) {
        return TransactionEvent.builder()
                .transactionId(UUID.randomUUID().toString())
                .accountId(request.getAccountId())
                .merchantId(request.getMerchantId())
                .amount(request.getAmount())
                .currency(request.getCurrency())
                .transactionType(request.getTransactionType())
                .sourceIp(request.getSourceIp())
                .deviceId(request.getDeviceId())
                .status(TransactionStatus.RECEIVED)
                .timestamp(LocalDateTime.now())
                .build();
    }
}