package com.sentinel.ingestionservice.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.sentinel.sentinelcommons.enums.TransactionStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Outbound DTO — what Sentinel returns to the caller
 * after successfully receiving a transaction.
 *
 * The caller receives a transaction ID and status
 * immediately. The fraud assessment happens
 * asynchronously — the caller does not wait for it.
 *
 * This is the non-blocking design pattern:
 * Submit → Receive acknowledgement → Poll for result
 *
 * In production the caller would either:
 * 1. Poll GET /api/v1/transactions/{id} for the result
 * 2. Receive a webhook callback when assessment completes
 *
 * Both patterns are built on this immediate response.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TransactionResponse {

    /**
     * Unique transaction ID generated by Sentinel.
     * The caller uses this to track the transaction
     * through the fraud assessment pipeline.
     */
    private String transactionId;

    /**
     * Current status in the pipeline.
     * Always RECEIVED on initial submission.
     */
    private TransactionStatus status;

    /**
     * Human-readable message for the caller.
     */
    private String message;

    /**
     * Exact timestamp of when Sentinel received
     * and accepted the transaction.
     */
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime receivedAt;
}