package com.sentinel.sentinelcommons.event;


import com.fasterxml.jackson.annotation.JsonFormat;
import com.sentinel.sentinelcommons.enums.TransactionStatus;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Kafka event published by ingestion-service to the
 * transactions.raw topic when a transaction is received
 * and validated.
 *
 * Consumed by:
 * - rules-engine-service  (applies fraud rules)
 * - scoring-service       (AI risk scoring)
 *
 * This is the entry point of the fraud detection
 * pipeline. Every transaction that enters Sentinel
 * starts as this event.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TransactionEvent {

    /**
     * Unique identifier generated by ingestion-service.
     * Used as the Kafka message key — ensures all events
     * for the same transaction go to the same partition,
     * preserving ordering.
     */
    private String transactionId;

    /**
     * The account initiating the transaction.
     * Used for velocity checks in the rules engine:
     * "how many transactions has this account made
     * in the last 60 seconds?"
     */
    private String accountId;

    /**
     * The merchant or recipient receiving the funds.
     */
    private String merchantId;

    /**
     * Transaction amount. BigDecimal for precision —
     * never use double or float for financial values.
     */
    private BigDecimal amount;

    /**
     * ISO 4217 currency code (e.g. NGN, USD, GBP).
     */
    private String currency;

    /**
     * Transaction type — TRANSFER, PAYMENT, WITHDRAWAL.
     * Different types carry different risk profiles.
     */
    private String transactionType;

    /**
     * IP address of the device that initiated the
     * transaction. Used for geographic anomaly detection.
     */
    private String sourceIp;

    /**
     * Unique identifier of the device used.
     * A new device ID on an established account
     * is a fraud signal.
     */
    private String deviceId;

    /**
     * Current pipeline status.
     * Set to RECEIVED when published by ingestion.
     */
    private TransactionStatus status;

    /**
     * Exact time the transaction was received.
     * ISO-8601 format in JSON serialization.
     */
    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime timestamp;
}